import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from "./loginBtn"
import LogoutBtn from "./logoutBtn"
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import RegisterBtn from './registerBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">PSH CRUD TEST</Link>
          <Link href="/list">List</Link>
          {
            session ? <span>Welcome, {session.user.name} <LogoutBtn></LogoutBtn></span> : <span><LoginBtn></LoginBtn> <Link href={'/register'}> <button>SIGN UP</button> </Link></span>
          }
        </div>
        {children}
      </body>

    </html>
  )
}


